Repository WITHUS-K/WITHUS-BE, pull requests merged in 2025-05, with the labels that each got.

#56 ✨지원서 질문 항목에 대한 응답 추가
  src/main/java/KUSITMS/WITHUS/domain/application/application/controller/ApplicationController.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/dto/ApplicationRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/dto/ApplicationResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/entity/Application.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/service/ApplicationService.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/service/ApplicationServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/application/applicationAnswer/dto/ApplicationAnswerRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/application/applicationAnswer/dto/ApplicationAnswerResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/application/applicationAnswer/entity/ApplicationAnswer.java
  src/main/java/KUSITMS/WITHUS/domain/application/applicationAnswer/repository/ApplicationAnswerJpaRepository.java
  src/main/java/KUSITMS/WITHUS/domain/application/applicationAnswer/repository/ApplicationAnswerRepository.java
  src/main/java/KUSITMS/WITHUS/domain/application/applicationAnswer/repository/ApplicationAnswerRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/documentQuestion/repository/DocumentQuestionRepository.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/documentQuestion/repository/DocumentQuestionRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/global/infra/upload/Uploader.java
  src/main/java/KUSITMS/WITHUS/global/infra/upload/service/FileUploadService.java
  src/main/java/KUSITMS/WITHUS/global/infra/upload/uploader/NcpObjectUploader.java
  src/main/java/KUSITMS/WITHUS/global/infra/upload/uploader/Uploader.java
  src/main/java/KUSITMS/WITHUS/global/infra/upload/util/FilePathBuilder.java
  src/main/resources/application-prod.yml
Labels: 🌟feature

#57 ✨ 타임 슬롯 조회
  src/main/java/KUSITMS/WITHUS/domain/application/application/dto/ApplicationResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/application/comment/repository/CommentRepository.java
  src/main/java/KUSITMS/WITHUS/domain/application/comment/repository/CommentRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslot/controller/TimeSlotController.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslot/repository/TimeSlotRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslot/service/TimeSlotService.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslot/service/TimeSlotServiceImpl.java
Labels: 🌟feature

#65 🐛 조직관리 수정 (1.5차 스프린트)
  src/main/java/KUSITMS/WITHUS/domain/organization/organizationRole/controller/OrganizationRoleController.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organizationRole/dto/OrganizationRoleRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organizationRole/dto/OrganizationRoleResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organizationRole/entity/OrganizationRole.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organizationRole/service/OrganizationRoleService.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organizationRole/service/OrganizationRoleServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/controller/UserController.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/dto/UserResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/entity/User.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/service/UserServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganization/controller/UserOrganizationController.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganization/dto/UserOrganizationRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganization/service/UserOrganizationService.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganization/service/UserOrganizationServiceImpl.java
  src/main/java/KUSITMS/WITHUS/global/common/annotation/DateTimeFormat.java
Labels: 🐛bug

#62 ✨ 공고에 Slug 값 추가
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/controller/RecruitmentController.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/dto/RecruitmentResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/entity/Recruitment.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/repository/RecruitmentRepository.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/repository/RecruitmentRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/service/RecruitmentService.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/service/RecruitmentServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/util/SlugGenerator.java
  src/main/java/KUSITMS/WITHUS/global/exception/ErrorCode.java
Labels: 🌟feature

#69 🐛 조직관리 2차 수정
  src/main/java/KUSITMS/WITHUS/domain/organization/organizationRole/controller/OrganizationRoleController.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organizationRole/dto/OrganizationRoleRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organizationRole/entity/OrganizationRole.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organizationRole/repository/OrganizationRoleRepository.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organizationRole/repository/OrganizationRoleRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organizationRole/service/OrganizationRoleService.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organizationRole/service/OrganizationRoleServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/controller/UserController.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/dto/UserResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganization/controller/UserOrganizationController.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganization/repository/UserOrganizationRepository.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganization/repository/UserOrganizationRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganization/service/UserOrganizationService.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganization/service/UserOrganizationServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganizationRole/repository/UserOrganizationRoleRepository.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganizationRole/repository/UserOrganizationRoleRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/global/exception/ErrorCode.java
Labels: 🐛bug

#68 🐛 공고 생성 관련 수정 (2차 스프린트)
  src/main/java/KUSITMS/WITHUS/domain/application/application/entity/Application.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/service/ApplicationServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/application/applicationAnswer/repository/ApplicationAnswerRepository.java
  src/main/java/KUSITMS/WITHUS/domain/application/applicationAnswer/repository/ApplicationAnswerRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/application/position/repository/PositionRepository.java
  src/main/java/KUSITMS/WITHUS/domain/application/position/service/PositionService.java
  src/main/java/KUSITMS/WITHUS/domain/application/position/service/PositionServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/evaluation/evaluationCriteria/controller/EvaluationCriteriaController.java
  src/main/java/KUSITMS/WITHUS/domain/evaluation/evaluationCriteria/dto/EvaluationCriteriaRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/evaluation/evaluationCriteria/dto/EvaluationCriteriaResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/evaluation/evaluationCriteria/entity/EvaluationCriteria.java
  src/main/java/KUSITMS/WITHUS/domain/evaluation/evaluationCriteria/service/EvaluationCriteriaService.java
  src/main/java/KUSITMS/WITHUS/domain/evaluation/evaluationCriteria/service/EvaluationCriteriaServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/interview/interview/service/InterviewSchedulerService.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslot/entity/TimeSlot.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslot/repository/TimeSlotRepository.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslot/repository/TimeSlotRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organization/entity/Organization.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/documentQuestion/controller/DocumentQuestionController.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/documentQuestion/dto/DocumentQuestionRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/documentQuestion/dto/DocumentQuestionResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/documentQuestion/entity/DocumentQuestion.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/documentQuestion/repository/DocumentQuestionRepository.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/documentQuestion/repository/DocumentQuestionRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/documentQuestion/service/DocumentQuestionService.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/documentQuestion/service/DocumentQuestionServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/position/controller/PositionController.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/position/dto/PositionRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/position/dto/PositionResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/position/entity/Position.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/position/repository/PositionJpaRepository.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/position/repository/PositionRepository.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/position/repository/PositionRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/position/service/PositionService.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/position/service/PositionServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/dto/RecruitmentRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/dto/RecruitmentResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/entity/Recruitment.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/service/RecruitmentServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/service/helper/AvailableTimeRangeAppender.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/service/helper/DocumentQuestionAppender.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/service/helper/EvaluationCriteriaAppender.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/service/helper/PositionAppender.java
Labels: 🐛bug

#71 🐛 공고 생성시 저장 전에 작업하던 문제 해결
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/service/RecruitmentServiceImpl.java
Labels: 🚨🚨emergency🚨🚨

#59 ✨ 마이페이지 (5차 스프린트)
  src/main/java/KUSITMS/WITHUS/domain/user/user/controller/UserController.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/dto/UserRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/dto/UserResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/entity/User.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/service/UserService.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/service/UserServiceImpl.java
  src/main/java/KUSITMS/WITHUS/global/exception/ErrorCode.java
  src/main/java/KUSITMS/WITHUS/global/infra/upload/service/FileUploadService.java
  src/main/java/KUSITMS/WITHUS/global/infra/upload/uploader/NcpObjectUploader.java
  src/main/java/KUSITMS/WITHUS/global/infra/upload/uploader/Uploader.java
  src/main/java/KUSITMS/WITHUS/global/infra/upload/util/FilePathBuilder.java
Labels: 🌟feature

#72 🐛 운영진 검색시 역할이 있는 운영진만 조회되는 문제 해결
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganization/repository/UserOrganizationRepositoryImpl.java
Labels: 🚨🚨emergency🚨🚨

#74 🐛 파일 업로드 검증 추가
  src/main/java/KUSITMS/WITHUS/domain/application/application/service/ApplicationServiceImpl.java
  src/main/java/KUSITMS/WITHUS/global/auth/jwt/JwtFilter.java
  src/main/java/KUSITMS/WITHUS/global/exception/ErrorCode.java
Labels: 🐛bug

#76 ✨ (사용자) 지원 현황 관리 (3차 스프린트)
  src/main/java/KUSITMS/WITHUS/domain/application/application/controller/ApplicationController.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/dto/ApplicationRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/dto/ApplicationResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/entity/Application.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/enumerate/AcademicStatus.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/enumerate/EvaluationStatus.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/repository/ApplicationJpaRepository.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/repository/ApplicationRepository.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/repository/ApplicationRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/service/ApplicationService.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/service/ApplicationServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/application/comment/controller/CommentController.java
  src/main/java/KUSITMS/WITHUS/domain/application/comment/dto/CommentRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/application/comment/dto/CommentResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/application/comment/entity/Comment.java
  src/main/java/KUSITMS/WITHUS/domain/application/comment/repository/CommentRepository.java
  src/main/java/KUSITMS/WITHUS/domain/application/comment/repository/CommentRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/application/comment/service/CommentService.java
  src/main/java/KUSITMS/WITHUS/domain/application/comment/service/CommentServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/evaluation/evaluation/controller/EvaluationController.java
  src/main/java/KUSITMS/WITHUS/domain/evaluation/evaluation/dto/EvaluationRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/evaluation/evaluation/repository/EvaluationJpaRepository.java
  src/main/java/KUSITMS/WITHUS/domain/evaluation/evaluation/service/EvaluationService.java
  src/main/java/KUSITMS/WITHUS/domain/evaluation/evaluation/service/EvaluationServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/evaluation/evaluationCriteria/dto/EvaluationCriteriaResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/evaluation/evaluationCriteria/enumerate/EvaluationScaleType.java
  src/main/java/KUSITMS/WITHUS/domain/evaluation/evaluationCriteria/repository/EvaluationCriteriaJpaRepository.java
  src/main/java/KUSITMS/WITHUS/domain/evaluation/evaluationCriteria/repository/EvaluationCriteriaRepository.java
  src/main/java/KUSITMS/WITHUS/domain/evaluation/evaluationCriteria/repository/EvaluationCriteriaRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/interview/interview/dto/InterviewScheduleDTO.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/availableTimeRange/dto/AvailableTimeRangeResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/dto/RecruitmentResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/entity/Recruitment.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/service/helper/EvaluationCriteriaAppender.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/dto/UserResponseDTO.java
  src/main/java/KUSITMS/WITHUS/global/common/annotation/DateFormatDot.java
  src/main/java/KUSITMS/WITHUS/global/common/annotation/DateFormatSlash.java
  src/main/java/KUSITMS/WITHUS/global/config/WebConfig.java
  src/main/java/KUSITMS/WITHUS/global/exception/ErrorCode.java
  src/main/java/KUSITMS/WITHUS/global/response/PagedResponse.java
  src/main/java/KUSITMS/WITHUS/global/response/PaginationMeta.java
Labels: 🌟feature

#78 🐛 JAR 내부에서도 classpath 리소스 읽을 수 있도록 수정
  src/main/java/KUSITMS/WITHUS/global/infra/email/template/MailTemplateProvider.java
Labels: 🚨🚨emergency🚨🚨

#79 ✨ 이메일 인증코드 템플릿 설정
  src/main/java/KUSITMS/WITHUS/global/auth/service/AuthServiceImpl.java
  src/main/java/KUSITMS/WITHUS/global/infra/email/template/MailTemplateType.java
  src/main/resources/templates/verification.html
Labels: 🌟feature

#80 ✨ (관리자) 지원 현황 관리 (2.5차 스프린트)
  src/main/java/KUSITMS/WITHUS/domain/application/application/controller/AdminApplicationController.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/controller/ApplicationController.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/dto/ApplicationRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/dto/ApplicationResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/entity/Application.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/enumerate/AdminApplicationSortField.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/enumerate/AdminStageFilter.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/enumerate/SimpleApplicationStatus.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/repository/ApplicationJpaRepository.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/service/ApplicationMailService.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/service/ApplicationService.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/service/ApplicationServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/service/ApplicationSmsService.java
  src/main/java/KUSITMS/WITHUS/domain/application/applicationAcquaintance/dto/ApplicationAcquaintanceResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/application/applicationAcquaintance/entity/ApplicationAcquaintance.java
  src/main/java/KUSITMS/WITHUS/domain/application/applicationAcquaintance/repository/ApplicationAcquaintanceJpaRepository.java
  src/main/java/KUSITMS/WITHUS/domain/application/applicationAcquaintance/repository/ApplicationAcquaintanceRepository.java
  src/main/java/KUSITMS/WITHUS/domain/application/applicationAcquaintance/repository/ApplicationAcquaintanceRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/application/applicationEvaluator/dto/ApplicationEvaluatorRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/application/applicationEvaluator/entity/ApplicationEvaluator.java
  src/main/java/KUSITMS/WITHUS/domain/application/applicationEvaluator/repository/ApplicationEvaluatorJpaRepository.java
  src/main/java/KUSITMS/WITHUS/domain/application/applicationEvaluator/repository/ApplicationEvaluatorRepository.java
  src/main/java/KUSITMS/WITHUS/domain/application/applicationEvaluator/repository/ApplicationEvaluatorRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/evaluation/evaluation/dto/EvaluationResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/mailTemplate/controller/MailTemplateController.java
  src/main/java/KUSITMS/WITHUS/domain/mailTemplate/dto/MailTemplateRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/mailTemplate/dto/MailTemplateResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/mailTemplate/entity/MailTemplate.java
  src/main/java/KUSITMS/WITHUS/domain/mailTemplate/repository/MailTemplateJpaRepository.java
  src/main/java/KUSITMS/WITHUS/domain/mailTemplate/service/MailTemplateService.java
  src/main/java/KUSITMS/WITHUS/domain/mailTemplate/service/MailTemplateServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organization/controller/OrganizationController.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/position/controller/PositionController.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/controller/RecruitmentController.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/dto/RecruitmentRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/dto/RecruitmentResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/entity/Recruitment.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/controller/UserController.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/dto/UserRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganizationRole/repository/UserOrganizationRoleJpaRepository.java
  src/main/java/KUSITMS/WITHUS/global/exception/ErrorCode.java
  src/main/java/KUSITMS/WITHUS/global/infra/email/sender/FakeMailSender.java
  src/main/java/KUSITMS/WITHUS/global/infra/email/sender/MailSender.java
  src/main/java/KUSITMS/WITHUS/global/infra/email/sender/SmtpMailSender.java
  src/main/java/KUSITMS/WITHUS/global/infra/sms/CoolSmsSender.java
  src/main/java/KUSITMS/WITHUS/global/infra/sms/FakeSmsSender.java
  src/main/java/KUSITMS/WITHUS/global/infra/sms/SmsSender.java
Labels: 🌟feature

#85 🐛 지원서 생성 관련 1차 수정 (2차 스프린트)
  src/main/java/KUSITMS/WITHUS/domain/recruitment/documentQuestion/dto/DocumentQuestionResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/position/dto/PositionResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/position/entity/Position.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/dto/RecruitmentRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/dto/RecruitmentResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/entity/Recruitment.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/service/RecruitmentServiceImpl.java
Labels: 🐛bug

#89 🐛 면접 관리 2차 수정
  src/main/java/KUSITMS/WITHUS/domain/interview/interview/controller/InterviewController.java
  src/main/java/KUSITMS/WITHUS/domain/interview/interview/dto/InterviewScheduleDTO.java
  src/main/java/KUSITMS/WITHUS/domain/interview/interview/repository/InterviewRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/interview/interview/service/InterviewSchedulerService.java
  src/main/java/KUSITMS/WITHUS/domain/interview/interviewAvailabiliy/service/InterviewerAvailabilityServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organization/controller/OrganizationController.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/controller/AdminRecruitmentController.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/controller/RecruitmentController.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/dto/RecruitmentResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/service/RecruitmentService.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/service/RecruitmentServiceImpl.java
  src/main/java/KUSITMS/WITHUS/global/auth/jwt/util/JwtUtil.java
  src/main/java/KUSITMS/WITHUS/global/config/RedisConfig.java
Labels: 🐛bug

#92 🐛 회원가입/로그인 (0차 스프린트) API 연동 - 로그인 응답 값 추가
  src/main/java/KUSITMS/WITHUS/domain/user/user/dto/UserResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/repository/UserRepository.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/repository/UserRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/global/auth/jwt/LoginFilter.java
  src/main/java/KUSITMS/WITHUS/global/config/SecurityConfig.java
Labels: 🐛bug

#93 🐛지원서 생성 2차 수정 (2차 스프린트)
  src/main/java/KUSITMS/WITHUS/domain/evaluation/evaluationCriteria/enumerate/EvaluationScaleType.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/dto/RecruitmentRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/dto/RecruitmentResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/entity/Recruitment.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/service/RecruitmentServiceImpl.java
Labels: 🐛bug

#91 ✅ 테스트 환경 구축
  build.gradle
  src/main/java/KUSITMS/WITHUS/domain/user/user/service/UserServiceImpl.java
  src/main/java/KUSITMS/WITHUS/global/util/redis/VerificationCache.java
  src/main/java/KUSITMS/WITHUS/global/util/redis/VerificationCacheUtil.java
  src/test/java/KUSITMS/WITHUS/domain/user/user/service/UserServiceImplTest.java
  src/test/java/KUSITMS/WITHUS/mock/container/TestContainer.java
  src/test/java/KUSITMS/WITHUS/mock/repository/FakeOrganizationRepository.java
  src/test/java/KUSITMS/WITHUS/mock/repository/FakeUserRepository.java
  src/test/java/KUSITMS/WITHUS/util/FakeVerificationCacheUtil.java
  src/test/java/KUSITMS/WITHUS/util/SecurityTestUtil.java
Labels: ✅test

#94 🐛 회원가입/로그인 (0차 스프린트) API 연동
  src/main/java/KUSITMS/WITHUS/domain/user/user/dto/UserResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/repository/UserRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganization/dto/UserOrganizationResponseDTO.java
  src/main/java/KUSITMS/WITHUS/global/auth/jwt/LoginFilter.java
  src/main/java/KUSITMS/WITHUS/global/auth/service/AuthService.java
  src/main/java/KUSITMS/WITHUS/global/auth/service/AuthServiceImpl.java
  src/main/java/KUSITMS/WITHUS/global/auth/service/CustomUserDetailsService.java
  src/main/java/KUSITMS/WITHUS/global/config/SecurityConfig.java
  src/main/java/KUSITMS/WITHUS/global/exception/ErrorCode.java
  src/test/java/KUSITMS/WITHUS/mock/repository/FakeUserRepository.java
Labels: 🐛bug, 🚨🚨emergency🚨🚨

#96 🐛 면접 관리 3차 수정
  src/main/java/KUSITMS/WITHUS/domain/interview/interview/controller/InterviewController.java
  src/main/java/KUSITMS/WITHUS/domain/interview/interview/dto/InterviewScheduleDTO.java
  src/main/java/KUSITMS/WITHUS/domain/interview/interview/service/InterviewSchedulerService.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslotUser/dto/TimeSlotUserResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/position/controller/PositionController.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/position/dto/PositionResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/position/entity/Position.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/position/enumerate/PositionColor.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/position/repository/PositionRepository.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/position/repository/PositionRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/position/service/PositionService.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/position/service/PositionServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/service/helper/PositionAppender.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/dto/UserResponseDTO.java
Labels: 🐛bug

#97 🐛 면접 관리 4차 수정
  src/main/java/KUSITMS/WITHUS/domain/interview/interview/entity/Interview.java
  src/main/java/KUSITMS/WITHUS/domain/interview/interview/service/InterviewSchedulerService.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslotUser/dto/TimeSlotUserResponseDTO.java
Labels: 🐛bug

#99 ✨ 관리자 지원 현황 관리 (2.5차 스프린트) 메일/문자 전송 기능 다듬기 및 로직 수정
  src/main/java/KUSITMS/WITHUS/domain/application/application/controller/AdminApplicationController.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/dto/ApplicationRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/dto/ApplicationResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/entity/Application.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/enumerate/AdminApplicationSortField.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/enumerate/AdminStageFilter.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/service/ApplicationMailService.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/service/ApplicationServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/service/ApplicationSmsService.java
  src/main/java/KUSITMS/WITHUS/domain/mailTemplate/controller/MailTemplateController.java
  src/main/java/KUSITMS/WITHUS/domain/mailTemplate/dto/MailTemplateResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/mailTemplate/entity/MailTemplate.java
  src/main/java/KUSITMS/WITHUS/domain/mailTemplate/repository/MailTemplateJpaRepository.java
  src/main/java/KUSITMS/WITHUS/domain/mailTemplate/service/MailTemplateService.java
  src/main/java/KUSITMS/WITHUS/domain/mailTemplate/service/MailTemplateServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/template/controller/TemplateController.java
  src/main/java/KUSITMS/WITHUS/domain/template/dto/TemplateRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/template/dto/TemplateResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/template/entity/Template.java
  src/main/java/KUSITMS/WITHUS/domain/template/enumerate/Medium.java
  src/main/java/KUSITMS/WITHUS/domain/template/repository/TemplateJpaRepository.java
  src/main/java/KUSITMS/WITHUS/domain/template/repository/TemplateRepository.java
  src/main/java/KUSITMS/WITHUS/domain/template/repository/TemplateRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/template/service/TemplateService.java
  src/main/java/KUSITMS/WITHUS/domain/template/service/TemplateServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/dto/UserResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/entity/User.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/enumerate/ProfileColor.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/service/UserServiceImpl.java
  src/main/java/KUSITMS/WITHUS/global/exception/ErrorCode.java
  src/main/java/KUSITMS/WITHUS/global/infra/sms/CoolSmsSender.java
Labels: 🌟feature

#100 🐛 면접 관리 5차 수정
  src/main/java/KUSITMS/WITHUS/domain/application/interviewQuestion/controller/InterviewQuestionController.java
  src/main/java/KUSITMS/WITHUS/domain/application/interviewQuestion/dto/InterviewQuestionRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/application/interviewQuestion/entity/InterviewQuestion.java
  src/main/java/KUSITMS/WITHUS/domain/application/interviewQuestion/repository/InterviewQuestionRepository.java
  src/main/java/KUSITMS/WITHUS/domain/application/interviewQuestion/repository/InterviewQuestionRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/application/interviewQuestion/service/InterviewQuestionService.java
  src/main/java/KUSITMS/WITHUS/domain/application/interviewQuestion/service/InterviewQuestionServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/interview/interview/controller/InterviewController.java
  src/main/java/KUSITMS/WITHUS/domain/interview/interview/dto/InterviewResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/interview/interview/entity/Interview.java
  src/main/java/KUSITMS/WITHUS/domain/interview/interview/service/InterviewSchedulerService.java
  src/main/java/KUSITMS/WITHUS/domain/interview/interview/service/InterviewService.java
  src/main/java/KUSITMS/WITHUS/domain/interview/interview/service/InterviewServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslotUser/controller/TimeSlotUserController.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslotUser/dto/TimeSlotUserRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslotUser/service/TimeSlotUserService.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslotUser/service/TimeSlotUserServiceImpl.java
  src/main/java/KUSITMS/WITHUS/global/exception/ErrorCode.java
Labels: 🐛bug

#102 ♻️ Repository 추상화
  src/main/java/KUSITMS/WITHUS/domain/application/applicantAvailability/entity/ApplicantAvailability.java
  src/main/java/KUSITMS/WITHUS/domain/application/applicantAvailability/repository/ApplicantAvailabilityRepository.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/dto/ApplicationResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/entity/Application.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/repository/ApplicationJpaRepository.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/repository/ApplicationRepository.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/repository/ApplicationRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/service/ApplicationServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/application/applicationAcquaintance/repository/ApplicationAcquaintanceJpaRepository.java
  src/main/java/KUSITMS/WITHUS/domain/application/applicationAcquaintance/repository/ApplicationAcquaintanceRepository.java
  src/main/java/KUSITMS/WITHUS/domain/application/applicationAcquaintance/repository/ApplicationAcquaintanceRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/application/applicationEvaluator/repository/ApplicationEvaluatorJpaRepository.java
  src/main/java/KUSITMS/WITHUS/domain/application/applicationEvaluator/repository/ApplicationEvaluatorRepository.java
  src/main/java/KUSITMS/WITHUS/domain/application/applicationEvaluator/repository/ApplicationEvaluatorRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/evaluation/evaluation/repository/EvaluationRepository.java
  src/main/java/KUSITMS/WITHUS/domain/evaluation/evaluation/repository/EvaluationRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/evaluation/evaluation/service/EvaluationServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/evaluation/evaluationCriteria/repository/EvaluationCriteriaRepository.java
  src/main/java/KUSITMS/WITHUS/domain/evaluation/evaluationCriteria/repository/EvaluationCriteriaRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/interview/interview/service/InterviewSchedulerService.java
  src/main/java/KUSITMS/WITHUS/domain/interview/interviewQuestion/controller/InterviewQuestionController.java
  src/main/java/KUSITMS/WITHUS/domain/interview/interviewQuestion/dto/InterviewQuestionRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/interview/interviewQuestion/dto/InterviewQuestionResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/interview/interviewQuestion/entity/InterviewQuestion.java
  src/main/java/KUSITMS/WITHUS/domain/interview/interviewQuestion/repository/InterviewQuestionJpaRepository.java
  src/main/java/KUSITMS/WITHUS/domain/interview/interviewQuestion/repository/InterviewQuestionRepository.java
  src/main/java/KUSITMS/WITHUS/domain/interview/interviewQuestion/repository/InterviewQuestionRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/interview/interviewQuestion/service/InterviewQuestionService.java
  src/main/java/KUSITMS/WITHUS/domain/interview/interviewQuestion/service/InterviewQuestionServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organization/service/OrganizationServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/position/repository/PositionRepository.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/position/repository/PositionRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/repository/RecruitmentRepository.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/repository/RecruitmentRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/recruitment/service/RecruitmentServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganization/repository/UserOrganizationRepository.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganization/repository/UserOrganizationRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganizationRole/repository/UserOrganizationRoleRepository.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganizationRole/repository/UserOrganizationRoleRepositoryImpl.java
Labels: ♻️refactor

#103 ✨ 관리자 지원 현황 관리 (2.5차 스프린트) 평가 담당자 분배 요청 이력 저장 및 조회 기능 구현
  src/main/java/KUSITMS/WITHUS/domain/application/application/controller/AdminApplicationController.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/entity/Application.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/service/ApplicationService.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/service/ApplicationServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/application/distributionRequest/dto/DistributionRequestResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/application/distributionRequest/entity/DistributionAssignment.java
  src/main/java/KUSITMS/WITHUS/domain/application/distributionRequest/entity/DistributionRequest.java
  src/main/java/KUSITMS/WITHUS/domain/application/distributionRequest/repository/DistributionRequestJpaRepository.java
  src/main/java/KUSITMS/WITHUS/domain/application/distributionRequest/repository/DistributionRequestRepository.java
  src/main/java/KUSITMS/WITHUS/domain/application/distributionRequest/repository/DistributionRequestRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/global/exception/ErrorCode.java
Labels: 🌟feature

#106 ✨ 파일 다운로드 api 구현
  src/main/java/KUSITMS/WITHUS/global/infra/upload/controller/FileController.java
Labels: 🌟feature

#107 🐛 파일 다운로드 request body로 받도록 수정
  src/main/java/KUSITMS/WITHUS/global/infra/upload/controller/FileController.java
  src/main/java/KUSITMS/WITHUS/global/infra/upload/dto/FileRequestDTO.java
Labels: 🐛bug

#109 🐛 사용자 지원 현황 관리 (3차 스프린트) api 연동
  src/main/java/KUSITMS/WITHUS/domain/application/application/controller/ApplicationController.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/dto/ApplicationResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/repository/ApplicationJpaRepository.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/repository/ApplicationRepository.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/repository/ApplicationRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/service/ApplicationMailService.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/service/ApplicationServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/service/ApplicationSmsService.java
Labels: 🐛bug

#114 ✨ 첨부파일 관련 오류 해결
  src/main/java/KUSITMS/WITHUS/global/infra/sms/CoolSmsSender.java
Labels: 🐛bug
