Repository WITHUS-K/WITHUS-BE, pull requests merged in 2025-08, with the labels that each got.

#136 ⚙️ Staging 환경 구축
  .github/workflows/staging.yml
  .gitignore
Labels: ⚙️chore

#138 ✨ (임시) 인사이더스 학회용 메일 템플릿 설정
  src/main/java/KUSITMS/WITHUS/domain/application/application/service/ApplicationServiceImpl.java
  src/main/java/KUSITMS/WITHUS/global/infra/email/template/MailTemplateType.java
  src/main/resources/templates/insiders-apply-success.html
Labels: 🚨🚨emergency🚨🚨

#141 🐛 TimeSlot 기능 수정
  src/main/java/KUSITMS/WITHUS/domain/application/application/dto/ApplicationResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/repository/ApplicationRepository.java
  src/main/java/KUSITMS/WITHUS/domain/application/application/repository/ApplicationRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslot/controller/TimeSlotController.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslot/dto/Applicant.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslot/dto/TimeSlotRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslot/dto/TimeSlotResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslot/entity/TimeSlot.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslot/service/TimeSlotService.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslot/service/TimeSlotServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslot/service/util/AssignmentRecorder.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslot/service/util/calendar/BusyCalendar.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslot/service/util/calendar/InMemoryBusyCalendar.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslot/service/util/candidate/CandidateIndex.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslot/service/util/candidate/CandidateSelector.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslot/service/util/selection/ordering/ScarcityFirstSlotOrderingStrategy.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslot/service/util/selection/ordering/SlotOrderingStrategy.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslot/service/util/selection/policy/FairnessPolicy.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslot/service/util/selection/policy/LeastAssignedFirstPolicy.java
  src/main/java/KUSITMS/WITHUS/domain/interview/timeslotUser/service/TimeSlotUserServiceImpl.java
Labels: 🐛bug, 🌟feature
