Repository WITHUS-K/WITHUS-BE, pull requests merged in 2025-04, with the labels that each got.

#7 🌟 Feat: JWT 기반 로그인 구현
  build.gradle
  gradlew
  src/main/java/KUSITMS/WITHUS/domain/user/entity/User.java
  src/main/java/KUSITMS/WITHUS/domain/user/repository/UserRepository.java
  src/main/java/KUSITMS/WITHUS/global/auth/controller/AdminController.java
  src/main/java/KUSITMS/WITHUS/global/auth/controller/JoinController.java
  src/main/java/KUSITMS/WITHUS/global/auth/controller/MainController.java
  src/main/java/KUSITMS/WITHUS/global/auth/dto/CustomUserDetails.java
  src/main/java/KUSITMS/WITHUS/global/auth/dto/JoinDTO.java
  src/main/java/KUSITMS/WITHUS/global/auth/enumerate/Role.java
  src/main/java/KUSITMS/WITHUS/global/auth/jwt/JwtFilter.java
  src/main/java/KUSITMS/WITHUS/global/auth/jwt/LoginFilter.java
  src/main/java/KUSITMS/WITHUS/global/auth/jwt/util/JwtUtil.java
  src/main/java/KUSITMS/WITHUS/global/auth/service/CustomUserDetailsService.java
  src/main/java/KUSITMS/WITHUS/global/auth/service/JoinService.java
  src/main/java/KUSITMS/WITHUS/global/config/SecurityConfig.java
  src/main/resources/application-prod.yml
Labels: 🌟feature

#13 ✨ CurrentUser Annotation 구현
  src/main/java/KUSITMS/WITHUS/domain/user/service/UserService.java
  src/main/java/KUSITMS/WITHUS/domain/user/service/UserServiceImpl.java
  src/main/java/KUSITMS/WITHUS/global/common/annotation/CurrentUser.java
  src/main/java/KUSITMS/WITHUS/global/common/annotation/resolver/AuthenticatedMemberResolver.java
  src/main/java/KUSITMS/WITHUS/global/config/WebConfig.java
Labels: 🌟feature

#11 ✨ Entity 초기 설계
  src/main/java/KUSITMS/WITHUS/WithusApplication.java
  src/main/java/KUSITMS/WITHUS/domain/application/entity/Application.java
  src/main/java/KUSITMS/WITHUS/domain/application/entity/ApplicationQuestion.java
  src/main/java/KUSITMS/WITHUS/domain/application/entity/ApplicationTemplate.java
  src/main/java/KUSITMS/WITHUS/domain/application/entity/Comment.java
  src/main/java/KUSITMS/WITHUS/domain/application/entity/Position.java
  src/main/java/KUSITMS/WITHUS/domain/application/enumerate/ApplicationStatus.java
  src/main/java/KUSITMS/WITHUS/domain/evaluation/entity/Evaluation.java
  src/main/java/KUSITMS/WITHUS/domain/evaluation/entity/EvaluationCriteria.java
  src/main/java/KUSITMS/WITHUS/domain/interview/entity/Interview.java
  src/main/java/KUSITMS/WITHUS/domain/interview/entity/InterviewQuestion.java
  src/main/java/KUSITMS/WITHUS/domain/interview/entity/TimeSlot.java
  src/main/java/KUSITMS/WITHUS/domain/organization/entity/Organization.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/entity/Recruitment.java
  src/main/java/KUSITMS/WITHUS/domain/user/entity/User.java
  src/main/java/KUSITMS/WITHUS/domain/user/entity/UserOrganization.java
  src/main/java/KUSITMS/WITHUS/global/common/BaseEntity.java
  src/main/java/KUSITMS/WITHUS/global/common/enumerate/Gender.java
  src/main/resources/application-prod.yml
Labels: 🌟feature

#15 🐛 예약어 피하기 위해 USER -> USERS로 변경
  src/main/java/KUSITMS/WITHUS/domain/user/entity/User.java
Labels: 🚨🚨emergency🚨🚨

#32 ✨ 회원가입 기능 구현
  .gitignore
  build.gradle
  src/main/java/KUSITMS/WITHUS/domain/organization/controller/OrganizationController.java
  src/main/java/KUSITMS/WITHUS/domain/organization/dto/OrganizationResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/organization/repository/OrganizationJpaRepository.java
  src/main/java/KUSITMS/WITHUS/domain/organization/repository/OrganizationRepository.java
  src/main/java/KUSITMS/WITHUS/domain/organization/repository/OrganizationRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/organization/service/OrganizationService.java
  src/main/java/KUSITMS/WITHUS/domain/organization/service/OrganizationServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/controller/UserController.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/dto/UserRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/dto/UserResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/repository/UserJpaRepository.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/repository/UserRepository.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/repository/UserRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/service/UserService.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/service/UserServiceImpl.java
  src/main/java/KUSITMS/WITHUS/global/common/enumerate/Gender.java
  src/main/java/KUSITMS/WITHUS/global/config/RedisConfig.java
  src/main/java/KUSITMS/WITHUS/global/config/SecurityConfig.java
  src/main/java/KUSITMS/WITHUS/global/exception/ErrorCode.java
  src/main/java/KUSITMS/WITHUS/global/exception/ExceptionAdvice.java
  src/main/java/KUSITMS/WITHUS/global/infra/sms/CoolSmsSender.java
  src/main/java/KUSITMS/WITHUS/global/infra/sms/FakeSmsSender.java
  src/main/java/KUSITMS/WITHUS/global/infra/sms/SmsSender.java
  src/main/java/KUSITMS/WITHUS/global/util/redis/VerificationCacheUtil.java
  src/main/resources/application-prod.yml
Labels: 🌟feature

#35 ⚙️ COOLSMS 관련 변수 전달
  .github/workflows/deploy.yml
Labels: ⚙️chore

#37 ⚙️Docker Compose로 배포
  .gitignore
  docker-compose.yml
Labels: ⚙️chore

#33 ✨ Refresh Token 구현
  src/main/java/KUSITMS/WITHUS/domain/user/user/controller/UserController.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/dto/UserRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/service/UserService.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/service/UserServiceImpl.java
  src/main/java/KUSITMS/WITHUS/global/auth/jwt/JwtFilter.java
  src/main/java/KUSITMS/WITHUS/global/auth/jwt/LoginFilter.java
  src/main/java/KUSITMS/WITHUS/global/auth/jwt/util/JwtUtil.java
  src/main/java/KUSITMS/WITHUS/global/config/CorsConfig.java
  src/main/java/KUSITMS/WITHUS/global/config/SecurityConfig.java
  src/main/java/KUSITMS/WITHUS/global/util/redis/RefreshTokenCacheUtil.java
Labels: ⚙️chore

#39 ⚙️서버에 docker-compose.yml 복사
  .github/workflows/deploy.yml
  docker-compose.yml
Labels: 🚨🚨emergency🚨🚨

#42 ✨ 조직 관리 관련 기능 구현 (1.5차)
  src/main/java/KUSITMS/WITHUS/domain/application/position/entity/Position.java
  src/main/java/KUSITMS/WITHUS/domain/application/position/service/PositionServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organization/controller/OrganizationController.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organization/dto/OrganizationRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organization/dto/OrganizationResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organization/entity/Organization.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organization/repository/OrganizationJpaRepository.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organization/repository/OrganizationRepository.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organization/repository/OrganizationRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organization/service/OrganizationService.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organization/service/OrganizationServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organizationRole/controller/OrganizationRoleController.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organizationRole/dto/OrganizationRoleRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organizationRole/dto/OrganizationRoleResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organizationRole/entity/OrganizationRole.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organizationRole/repository/OrganizationRoleJpaRepository.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organizationRole/repository/OrganizationRoleRepository.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organizationRole/repository/OrganizationRoleRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organizationRole/service/OrganizationRoleService.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organizationRole/service/OrganizationRoleServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/entity/Recruitment.java
  src/main/java/KUSITMS/WITHUS/domain/recruitment/service/RecruitmentServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/dto/UserResponseDTO.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/entity/User.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/service/UserService.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/service/UserServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganization/controller/UserOrganizationController.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganization/dto/UserOrganizationRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganization/entity/UserOrganization.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganization/repository/UserOrganizationRepository.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganization/repository/UserOrganizationRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganization/service/UserOrganizationService.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganization/service/UserOrganizationServiceImpl.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganizationRole/entity/UserOrganizationRole.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganizationRole/repository/UserOrganizationRoleJpaRepository.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganizationRole/repository/UserOrganizationRoleRepository.java
  src/main/java/KUSITMS/WITHUS/domain/user/userOrganizationRole/repository/UserOrganizationRoleRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/global/exception/ErrorCode.java
Labels: 🌟feature

#40 ✨ 비밀번호 찾기(재설정) 기능 구현 및 회원가입 시 조직 중복 에러 처리
  src/main/java/KUSITMS/WITHUS/domain/organization/organization/repository/OrganizationJpaRepository.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organization/repository/OrganizationRepository.java
  src/main/java/KUSITMS/WITHUS/domain/organization/organization/repository/OrganizationRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/controller/UserController.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/dto/UserRequestDTO.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/entity/User.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/repository/UserRepository.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/repository/UserRepositoryImpl.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/service/UserService.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/service/UserServiceImpl.java
  src/main/java/KUSITMS/WITHUS/global/exception/ErrorCode.java
  src/main/java/KUSITMS/WITHUS/global/infra/email/FakeMailSender.java
  src/main/java/KUSITMS/WITHUS/global/infra/email/MailSender.java
  src/main/java/KUSITMS/WITHUS/global/infra/email/SmtpMailSender.java
  src/main/resources/application-prod.yml
Labels: 🌟feature

#44 ♻️ 회원/인증 엔드포인트 분리
  src/main/java/KUSITMS/WITHUS/domain/user/user/controller/UserController.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/service/UserService.java
  src/main/java/KUSITMS/WITHUS/domain/user/user/service/UserServiceImpl.java
  src/main/java/KUSITMS/WITHUS/global/auth/controller/AuthController.java
  src/main/java/KUSITMS/WITHUS/global/auth/service/AuthService.java
  src/main/java/KUSITMS/WITHUS/global/auth/service/AuthServiceImpl.java
  src/main/java/KUSITMS/WITHUS/global/config/SecurityConfig.java
  src/main/resources/application-prod.yml
Labels: ♻️refactor

#45 ⚙️ Mail 관련 배포 환경변수 관리
  .github/workflows/deploy.yml
  docker-compose.yml
Labels: ⚙️chore

#49 ⚙️ CORS 설정 주소 추가
  src/main/java/KUSITMS/WITHUS/global/config/CorsConfig.java
Labels: ⚙️chore
